<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <groupId>org.ssssssss</groupId>
    <artifactId>magic-script</artifactId>
    <version>2.0.0</version>
    <packaging>jar</packaging>

    <name>magic-script</name>
    <description>magic script</description>
    <url>https://gitee.com/ssssssss-team/magic-script</url>
    <inceptionYear>2020</inceptionYear>

    <licenses>
        <license>
            <name>The MIT License (MIT)</name>
            <url>https://gitee.com/ssssssss-team/magic-script/blob/master/LICENSE</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>jiamuliuquan</name>
            <email>JSpringYC@gmail.com</email>
        </developer>
        <developer>
            <name>jmxd</name>
            <email>838425805@qq.com</email>
        </developer>
    </developers>
    <scm>
        <url>https://gitee.com/ssssssss-team/magic-script</url>
        <connection>scm:git:https://gitee.com/ssssssss-team/magic-script.git</connection>
        <developerConnection>scm:git:https://gitee.com/ssssssss-team/magic-script.git</developerConnection>
    </scm>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <!--Compiler-->
                    <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <release>1.8</release>
                            <encoding>UTF-8</encoding>
                        </configuration>
                    </plugin>
                    <!-- Source -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- Java Doc -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <configuration>
                            <additionalOptions>
                                <additionalOption>-Xdoclint:none</additionalOption>
                            </additionalOptions>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
